name: nextjs-project-improvements_workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  linter_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Run linter
        run: npm run lint

  cypress_job:
    needs: linter_job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Start Next.js server
        run: npm run dev &
        env:
          PORT: 3000

      - name: Wait for server to be ready
        run: npx wait-on http://localhost:3000

      - name: Run Cypress tests
        uses: cypress-io/github-action@v4
        with:
          browser: chrome
          spec: cypress/integration/1-my-tests/**/*.spec.js
        continue-on-error: true

      - name: Save Cypress results to artifact
        run: |
          echo "Saving Cypress results..."
          npx cypress run --spec 'cypress/integration/1-my-tests/**/*.spec.js' > result.txt || echo "Cypress tests failed"
        continue-on-error: true

      - name: Upload Cypress artifact
        uses: actions/upload-artifact@v3
        with:
          name: cypress-results
          path: result.txt

  add_badge_job:
    needs: cypress_job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download Cypress artifact
        uses: actions/download-artifact@v3
        with:
          name: cypress-results

      - name: Determine Cypress result
        id: read_result
        run: |
          echo "Reading Cypress result..."
          if grep -q "failure" result.txt; then
            echo "::set-output name=cypress_outcome::failure"
          else
            echo "::set-output name=cypress_outcome::success"
          fi

      - name: Update README with badge
        run: |
          echo "Updating README.md..."
          if [ "${{ steps.read_result.outputs.cypress_outcome }}" = "failure" ]; then
            echo "\n\nRESULTAT DELS ÚLTIMS TESTS\n\n![Test Badge](https://img.shields.io/badge/test-failure-red)" >> README.md
          else
            echo "\n\nRESULTAT DELS ÚLTIMS TESTS\n\n![Test Badge](https://img.shields.io/badge/tested%20with-Cypress-04C38E.svg)" >> README.md
          fi

      - name: Commit updated README
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          git config --global user.email "alvgarcam@alu.edu.gva.es"
          git config --global user.name "AlvaroGarCam"
          git remote set-url origin https://${{ secrets.PAT_TOKEN }}@github.com/${{ github.repository }}
          git remote -v
          git add README.md
          git commit -m "Update README.md with Cypress test results" || echo "No changes to commit"
          git push origin main
